Repository ThaiRepose/thairepose, pull requests merged in 2021-11, with the labels that each got.

#15 New authentication with Oauth
  .gitignore
  README.md
  config.cfg
  requirements.txt
  threpose/settings.py
  threpose/urls.py
  users/adapter.py
  users/forms.py
  users/models.py
  users/static/profile_pic/blank-profile-picture.png
  users/templates/account/account_inactive.html
  users/templates/account/base.html
  users/templates/account/email.html
  users/templates/account/email/base_message.txt
  users/templates/account/email/email_confirmation_message.txt
  users/templates/account/email/email_confirmation_signup_message.txt
  users/templates/account/email/email_confirmation_signup_subject.txt
  users/templates/account/email/email_confirmation_subject.txt
  users/templates/account/email/password_reset_key_message.txt
  users/templates/account/email/password_reset_key_subject.txt
  users/templates/account/email_confirm.html
  users/templates/account/login.html
  users/templates/account/logout.html
  users/templates/account/messages/cannot_delete_primary_email.txt
  users/templates/account/messages/email_confirmation_sent.txt
  users/templates/account/messages/email_confirmed.txt
  users/templates/account/messages/email_deleted.txt
  users/templates/account/messages/logged_in.txt
  users/templates/account/messages/logged_out.txt
  users/templates/account/messages/password_changed.txt
  users/templates/account/messages/password_set.txt
  users/templates/account/messages/primary_email_set.txt
  users/templates/account/messages/unverified_primary_email.txt
  users/templates/account/password_change.html
  users/templates/account/password_reset.html
  users/templates/account/password_reset_done.html
  users/templates/account/password_reset_from_key.html
  users/templates/account/password_reset_from_key_done.html
  users/templates/account/password_set.html
  users/templates/account/signup.html
  users/templates/account/signup_closed.html
  users/templates/account/snippets/already_logged_in.html
  users/templates/account/verification_sent.html
  users/templates/account/verified_email_required.html
  users/templates/users/activate.html
  users/templates/users/activation-fail.html
  users/templates/users/login.html
  users/templates/users/register.html
  users/templates/users/temp_home.html
  users/tests.py
  users/utils.py
  users/views.py
Labels: enhancement

#14 New Feature: Place Details page.
  README.md
  theme/static_src/tailwind.config.js
  theme/templates/base.html
  trip/static/trip/css/container_blocks.css
  trip/static/trip/images/img_not_found.jpg
  trip/templates/trip/place_details.html
  trip/tests.py
  trip/urls.py
  trip/views.py
Labels: enhancement, iteration 3

#18 New Feature: Review
  .gitignore
  .travis.yml
  trip/admin.py
  trip/models.py
  trip/templates/trip/add_blog.html
  trip/templates/trip/add_review.html
  trip/templates/trip/trip_detail.html
  trip/templates/trip/trip_plan.html
  trip/tests.py
  trip/urls.py
  trip/views.py
Labels: enhancement, iteration 3

#27 UI Improvement: navigation links and appearance in Navigation bar
  theme/templates/base.html
Labels: enhancement

#32 Login register page.
  users/templates/account/login.html
  users/templates/account/signup.html
Labels: enhancement

#36 Improve login register
  requirements.txt
  threpose/settings.py
  users/static/template-picture/beach_picture.jpg
  users/static/template-picture/tr-logo.png
  users/templates/account/login.html
  users/templates/account/signup.html
Labels: enhancement

#40 Fix login page and redirect URL after signup
  users/adapter.py
  users/templates/account/login.html
  users/templates/account/signup.html
Labels: bug

#31 Reset password page
  users/static/template-picture/favpng_check-mark-tick.png
  users/templates/account/password_change.html
  users/templates/account/password_reset.html
  users/templates/account/password_reset_done.html
  users/templates/account/password_reset_from_key.html
  users/templates/account/password_reset_from_key_done.html
  users/templates/account/password_set.html
Labels: enhancement

#47 Add github action
  .github/workflows/django.yml
Labels: enhancement

#35 UI Bug Fix: Trip place details
  theme/static_src/tailwind.config.js
  trip/static/trip/css/container_blocks.css
  trip/templates/trip/place_details.html
Labels: enhancement

#50 Completed draft: Trip Organizer
  planner/__init__.py
  planner/admin.py
  planner/apps.py
  planner/models.py
  planner/templates/planner/edit_planner.html
  planner/templates/planner/trip_planner_list.html
  planner/templates/planner/view_planner.html
  planner/tests.py
  planner/urls.py
  planner/views.py
  theme/templates/base.html
  threpose/settings.py
  threpose/urls.py
  trip/static/trip/css/container_blocks.css
  trip/templates/trip/index.html
  trip/templates/trip/place_details.html
  trip/urls.py
  trip/views.py
Labels: Iteration 5

#60 Frontend blog update plan
  .gitignore
  config.cfg
  threpose/settings.py
  threpose/urls.py
  trip/forms.py
  trip/templates/trip/add_blog.html
  trip/templates/trip/update_plan.html
  trip/views.py
Labels: enhancement

#62 Trip plan and detail
  .gitignore
  media/pic/.gitkeep
  search/admin.py
  search/api.py
  search/apps.py
  search/templates/search/place_list.html
  search/urls.py
  search/views.py
  src/caching/README.md
  src/caching/caching_gmap.py
  src/caching/main.py
  src/caching/setup.py
  theme/static/css/main.css
  threpose/settings.py
  trip/models.py
  trip/static/test_pic/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg
  trip/static/trip/css/container_blocks.css
  trip/templates/trip/index.html
  trip/templates/trip/trip_detail.html
  trip/templates/trip/trip_plan.html
  trip/tests.py
  trip/urls.py
  trip/views.py
Labels: enhancement

#66 Confirm email
  users/templates/account/email_confirm.html
  users/templates/account/verified_email_required.html
Labels: enhancement

#52 New Feature: Profile Edit
  .gitignore
  theme/static_src/package-lock.json
  threpose/settings.py
  threpose/urls.py
  users/forms.py
  users/models.py
  users/templates/users/edit_profile.html
  users/templates/users/profile.html
  users/tests.py
  users/utils.py
  users/views.py
Labels: enhancement, Iteration 5

#69 Fix frontend index.html
  trip/templates/trip/index.html
Labels: bug

#83 finish term of service page
  theme/templates/base.html
  threpose/urls.py
  users/templates/policy/term_of_service.html
  users/views.py
Labels: enhancement

#67 New Feature Completed: Trip Organizer
  README.md
  planner/admin.py
  planner/models.py
  planner/static/planner/css/editor.css
  planner/static/planner/css/style.css
  planner/static/planner/js/main.js
  planner/static/planner/js/planner_editor.js
  planner/templates/planner/edit_planner.html
  planner/templates/planner/trip_planner_list.html
  planner/templates/planner/view_planner.html
  planner/tests.py
  planner/tests/__init__.py
  planner/tests/test_backend.py
  planner/tests/test_edit.py
  planner/tests/test_index.py
  planner/tests/test_models.py
  planner/views.py
  theme/static/css/main.css
  threpose/settings.py
Labels: enhancement, Iteration 6

#86 Additional pages
  theme/templates/about-us.html
  theme/templates/base.html
  theme/templates/feedback.html
  theme/views.py
  threpose/urls.py
Labels: Iteration 7

#92 UI Improvement: Homepage UI
  search/api.py
  trip/templates/trip/index.html
  trip/urls.py
  trip/views.py
Labels: Iteration 7

#96 New Function: Place reviews
  theme/templates/base.html
  trip/admin.py
  trip/models.py
  trip/templates/trip/place_details.html
  trip/tests.py
  trip/urls.py
  trip/views.py
Labels: Iteration 7

#97 finish improve security when delete and fix miss spelling
  trip/templates/trip/trip_detail.html
  trip/templates/trip/update_plan.html
  trip/views.py
Labels: enhancement

#101 Social signup page
  users/templates/socialaccount/signup.html
Labels: bug, enhancement

#109 Fix like feature and add unit test for add post
  trip/templates/trip/trip_detail.html
  trip/tests.py
  trip/views.py
Labels: bug
